# Generated by Django 5.2.3 on 2025-06-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=10, unique=True)),
                ('member_name', models.CharField(max_length=255)),
                ('member_phone', models.CharField(max_length=15, unique=True)),
                ('member_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(max_length=500)),
                ('payment_status', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
