# Generated by Django 5.2.3 on 2025-06-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosqueapp', '0003_monthlypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAmountSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
