# Generated by Django 5.2.3 on 2025-06-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosqueapp', '0004_monthlyamountsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='paid_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
